stages:
  - build
  - deploy

variables:
  KUBE_NAMESPACE: "angkas-dev"
  KUBECONFIG: "~/.kube/config"

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/peter-cipriano/angkas:${CI_COMMIT_SHA} .
    - docker push registry.gitlab.com/peter-cipriano/angkas:${CI_COMMIT_SHA}
  only:
    - main

deploy:
  stage: deploy
  script:
    - helm upgrade --install angkas ./angkas \
        --set image.repository=registry.gitlab.com/peter-cipriano/angkas \
        --set image.tag=${CI_COMMIT_SHA} \
        --namespace $KUBE_NAMESPACE
  only:
    - main
